name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.10"

jobs:
  
  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3.3.0"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v3.3.0"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"